[package]
name = "albot"
version = "0.1.0"
edition = "2021"

[dependencies]
descord = { git = "https://github.com/DescordLib/descord", version = "0.1.10" }
tokio = {version = "1", features = ["full"]}
